### Get all tasks
GET https://cse341-week3-4-project.onrender.com

### Get single task
GET https://cse341-week3-4-project.onrender.com/tasks/69bc4b7b1cd467fbf1d040f7

### Create a task
POST https://cse341-week3-4-project.onrender.com/tasks
Content-Type: application/json

{
  "title": "Test Task2",
  "description": "Testing timestamps2",
  "status": "pending",
  "priority": "high",
  "dueDate": "2026-03-25",
  "userId": "test-user-1"
}

### Update a task
PUT https://cse341-week3-4-project.onrender.com/tasks/69bc4b7b1cd467fbf1d040f7
Content-Type: application/json

{
  "title": "Updated Task"
}

### Delete a task
DELETE https://cse341-week3-4-project.onrender.com/tasks/69bc4bbd1cd467fbf1d040f9