### Get all tasks
GET https://cse341-week3-4-project.onrender.com/tasks
user-id: 69c6b69076ce36cfb3474cdc

### Get single task
GET https://cse341-week3-4-project.onrender.com/tasks/69be64885ccf7087364cd01a
user-id: 69be61c55ccf7087364ccfff

### Create a task
POST https://cse341-week3-4-project.onrender.com/tasks
user-id: 69c6b69076ce36cfb3474cdc
Content-Type: application/json

{
  "title": "finish project",
  "description": "cse341 project due soon",
  "status": "pending",
  "priority": "high",
  "dueDate": "2026-03-25"
}

### Update a task
PUT https://cse341-week3-4-project.onrender.com/tasks/69be64885ccf7087364cd01a
user-id: 69be64355ccf7087364cd016
Content-Type: application/json

{
  "title": "room needs sweeping"
}

### Delete a task
DELETE https://cse341-week3-4-project.onrender.com/tasks/69be64885ccf7087364cd01a
user-id: 69be64355ccf7087364cd016